#**Numpy 1**

---







In [0]:
import numpy as np

In [0]:
my_list = [1,2,3,4]

In [3]:
type(my_list)

list

In [0]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

#**Numpy 2**

---



In [8]:
np.arange(0,11) #simple range from 0 to 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.random.randint(0,10) #Output random value between 0 to 10

9

In [13]:
np.random.randint(0,1000,(4,4)) #to generate array of random number

array([[651, 969, 273, 368],
       [591,  47, 344, 670],
       [811, 259, 329, 493],
       [915, 863, 292, 194]])

In [0]:
np.random.seed(101)

In [15]:
np.random.randint(0,100,10) #generate 10 random samples between no 0 to 100

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [16]:
arr

array([1, 2, 3, 4])

In [17]:
arr.max()

4

In [18]:
arr.min()

1

In [19]:
arr.mean()

2.5

In [20]:
arr.argmax() # returns index value of maximum element

3

In [21]:
arr.argmin() # returns index value of minimum element

0

In [22]:
arr.reshape(2,5) #Error cannot reshape array of size 4 into shape (2,5) please give dimesions which are compatible 

ValueError: ignored

In [24]:
arr.reshape(2,2) # Convert the array to matrix

array([[1, 2],
       [3, 4]])

In [0]:
mat = np.arange(0,100).reshape(10,10)

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat[0,0]

0

In [28]:
mat[2,0]

20

In [29]:
mat[:,0] # Entire 0th column

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
mat[0,:] # Entire 0th row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [32]:
np.eye(3) # Index matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.diag(mat) # Returns diagonal elements

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [34]:
np.linspace(0,4,9) # Divide the 0-4 range in 9 equal parts

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [35]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [0]:
p = np.ones([2,3],int)

In [37]:
p

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
np.vstack([p,2*p]) #vertical stack

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [39]:
p.T

array([[1, 1],
       [1, 1],
       [1, 1]])

In [40]:
p.dtype # Shows the data type

dtype('int64')

In [0]:
p = p.astype('f') #change the type

In [42]:
p

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [43]:
p.dtype

dtype('float32')

In [0]:
a = np.arange(0,100).reshape(10,10)

In [46]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [0]:
b = a[:3,:3] 

In [54]:
b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [0]:
b[:] = 0  #changeing the value of b will change the value of a

In [56]:
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
a

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [0]:
a_copy = a.copy() # Change in the value of a copy will not change the value of a

In [60]:
a_copy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [0]:
a_copy[:3,:3] = 1

In [65]:
a_copy

array([[ 1,  1,  1,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  1,  1, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  1,  1, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
a

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])